# Generated by Django 3.2.8 on 2022-04-22 15:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20220422_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='probleme',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='probleme',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Probleme_image_xy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('Probleme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.probleme')),
            ],
        ),
    ]
