# Generated by Django 3.2.8 on 2022-05-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark_x_y',
            name='num',
            field=models.IntegerField(default=1),
        ),
    ]
