# Generated by Django 3.2.8 on 2022-05-06 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marks', '0002_mark_x_y_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark_x_y',
            old_name='Probleme_id',
            new_name='probleme',
        ),
        migrations.AddField(
            model_name='mark',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mark',
            name='gravity',
            field=models.IntegerField(),
        ),
    ]
