# Generated by Django 3.2.8 on 2022-05-06 20:37

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_auto_20220506_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='created_at',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
