# Generated by Django 3.2.8 on 2022-05-06 23:30

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0011_alter_mark_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/marks'), upload_to=''),
        ),
    ]
