# Generated by Django 3.2.8 on 2022-05-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0012_alter_mark_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mark_x_y',
            new_name='Point',
        ),
        migrations.AlterField(
            model_name='mark',
            name='image',
            field=models.ImageField(upload_to='marks/'),
        ),
    ]
