# Generated by Django 3.2.8 on 2022-05-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0013_auto_20220513_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='probleme',
            new_name='mark',
        ),
    ]
