# Generated by Django 3.2.8 on 2022-05-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0014_rename_probleme_point_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='descx',
            field=models.FloatField(default=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='descy',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
